before:
  hooks:
    - /bin/sh -c "echo -n {{.Tag}} > misc/version"

builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    binary: ghupload
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w
      - -s
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: ghupload
    tap:
      owner: chmouel
      name: ghupload
    folder: Formula
    homepage: "https://github.com/chmouel/ghupload"
    description: ghupload  - smee.io go client
    install: |
      bin.install "ghupload" => "ghupload"
      output = Utils.popen_read("SHELL=bash #{bin}/ghupload completion bash")
      (bash_completion/"ghupload").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/ghupload completion zsh")
      (zsh_completion/"_ghupload").write output
      prefix.install_metafiles

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  prerelease: "false"

nfpms:
  - file_name_template: "ghupload-{{.Version}}_{{.Os}}-{{.Arch}}"
    homepage: https://github.com/chmouel/ghupload
    description: "ghupload - smee.io forwarder in go"
    maintainer: Chmouel Boudjnah <chmouel@chmouel.com>
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Brew formula update"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - Update README.md

universal_binaries:
  - replace: true
    name_template: "ghupload"

aurs:
  - name: ghupload-bin
    homepage: "https://github.com/chmouel/ghupload"
    description: "ghupload - smee.io forwarder in go"
    maintainers:
      - "Chmouel Boudjnah <chmouel@chmouel.com>"
    license: Apache 2.0
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/ghupload-bin.git
    package: |-
      # bin
      install -Dm755 "./ghupload" "${pkgdir}/usr/bin/ghupload"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/ghupload/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"

      ./ghupload completion zsh > ghupload.zsh
      ./ghupload completion bash > ghupload.bash

      install -Dm644 "ghupload.bash" "${pkgdir}/usr/share/bash-completion/completions/ghupload"
      install -Dm644 "ghupload.zsh" "${pkgdir}/usr/share/zsh/site-functions/_ghupload"
