# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghupload < Formula
  desc "ghupload  - smee.io go client"
  homepage "https://github.com/chmouel/ghupload"
  version "0.1.0"

  on_macos do
    url "https://github.com/chmouel/ghupload/releases/download/v0.1.0/ghupload_0.1.0_MacOS_all.tar.gz"
    sha256 "a3d3ea2169d28b6aedc0faad7dbb2bf5c1c795bf7443ff139626a43c732b8c2c"

    def install
      bin.install "ghupload" => "ghupload"
      output = Utils.popen_read("SHELL=bash #{bin}/ghupload completion bash")
      (bash_completion/"ghupload").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/ghupload completion zsh")
      (zsh_completion/"_ghupload").write output
      prefix.install_metafiles
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chmouel/ghupload/releases/download/v0.1.0/ghupload_0.1.0_Linux_x86_64.tar.gz"
      sha256 "83ee03e2d99bf1db3e74506a3ef2fdeb41c1f0451febee0d4bd0ee1fa989e210"

      def install
        bin.install "ghupload" => "ghupload"
        output = Utils.popen_read("SHELL=bash #{bin}/ghupload completion bash")
        (bash_completion/"ghupload").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/ghupload completion zsh")
        (zsh_completion/"_ghupload").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chmouel/ghupload/releases/download/v0.1.0/ghupload_0.1.0_Linux_arm64.tar.gz"
      sha256 "551747c106f2a7fc7b21019729238907b54c6b6b4e30befbbaa1248f41ef66c1"

      def install
        bin.install "ghupload" => "ghupload"
        output = Utils.popen_read("SHELL=bash #{bin}/ghupload completion bash")
        (bash_completion/"ghupload").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/ghupload completion zsh")
        (zsh_completion/"_ghupload").write output
        prefix.install_metafiles
      end
    end
  end
end
