# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosmee < Formula
  desc "gosmee  - smee.io go client"
  homepage "https://github.com/chmouel/ghupload"
  version "0.0.1"

  on_macos do
    url "https://github.com/chmouel/ghupload/releases/download/v0.0.1/ghupload_0.0.1_MacOS_all.tar.gz"
    sha256 "5c4d4d0fb22f0a3bdca5fef6f35361c512e2c3f34d297920f5e211204a5ed9ab"

    def install
      bin.install "ghupload"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chmouel/ghupload/releases/download/v0.0.1/ghupload_0.0.1_Linux_arm64.tar.gz"
      sha256 "b7e85c9d39a2e9bc024cb4a532f93f788e81d3e962f5fb62c492167ac57439ee"

      def install
        bin.install "ghupload"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chmouel/ghupload/releases/download/v0.0.1/ghupload_0.0.1_Linux_x86_64.tar.gz"
      sha256 "db6b9e07fa4d2efd03d5d0a8d3604adb9d2c963177e28c464520bf072121664c"

      def install
        bin.install "ghupload"
      end
    end
  end
end
